storage: /home/.local/share/verdaccio/storage

auth:
  gitlab:
    url: https://git.fesc.io

packages:
   '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
    gitlab: true